# Generated by Django 5.0.6 on 2024-05-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
